
[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "arslabrobotics"
version = "2.0.0"
authors = [
  { name="Corrado Santoro", email="corrado.santoro@unict.it" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]
dependencies = [
    "matplotlib>=3.11.1",
    "opencv-python>=4.14.0.94",
    "numpy>=2.5.2",
    
]
[project.optional-dependencies]
docs = [
    "sphinx>=7.2.6",
    "sphinx-rtd-theme>=2.0.0",
]
